Single JSON per playlist version, with dev cache

diff --git a/get-playlists b/get-playlists
--- a/get-playlists
+++ b/get-playlists
@@ -13,22 +13,23 @@ spotify_get() {
 }
 
 playlists() {
-  spotify_get https://api.spotify.com/v1/me/playlists > "${out_dir}/playlists.json"
-  if [ "$?" != "0" ]; then
-    echo 'Playlist get failed' > /dev/stderr
-    exit 111
+  if [ ! -e "${out_dir}/playlists.json" ]; then
+    spotify_get https://api.spotify.com/v1/me/playlists > "${out_dir}/playlists.json"
+    if [ "$?" != "0" ]; then
+      echo 'Playlist get failed' > /dev/stderr
+      exit 111
+    fi
   fi
 
   cat "${out_dir}/playlists.json"
 }
 
-playlist_items() {
-  playlists |
-    jq -r '.items[] | @sh "id=\(.id) href=\(.tracks.href) name=\(.name)"'
+playlist_vars() {
+  jq -r '@sh "id=\(.id) href=\(.tracks.href) name=\(.name)"'
 }
 
-playlist_items | while read -r playlist_line; do
-  eval "$playlist_line"
+playlists | jq -c '.items[]' | while read -r playlist_item; do
+  eval "$(echo $playlist_item | playlist_vars)"
   echo "Getting playlist $name ($id)" > /dev/stderr
 
   n=0
@@ -36,11 +37,12 @@ playlist_items | while read -r playlist_line; do
 
   while [ "$next_url" != "null" ]; do
     outfile="${out_dir}/${id}-tracks-${n}.json"
-    spotify_get $next_url > $outfile
-
-    if [ "$?" != "0" ]; then
-      echo 'API call failed' > /dev/stderr
-      exit 111
+    if [ ! -e "$outfile" ]; then
+      spotify_get $next_url > $outfile
+      if [ "$?" != "0" ]; then
+        echo 'API call failed' > /dev/stderr
+        exit 111
+      fi
     fi
 
     next_url=$(jq -r '.next' < $outfile)
@@ -48,8 +50,10 @@ playlist_items | while read -r playlist_line; do
   done
 
   cat $out_dir/$id-tracks-*.json |
-    jq -c '.items[]' |
-    jq --arg name "$name" --slurp '{ name: $name, items: . }' \
-    > "${out_dir}/${id}.json" &&
-  rm ${out_dir}/${id}-tracks-*.json
+    jq -c '.items[]' > "${out_dir}/${id}-tracks.json"
+
+  echo $playlist_item |
+    jq --slurpfile items ${out_dir}/${id}-tracks.json \
+      '. + { items: $items }' > "${out_dir}/${id}.json"
+#  rm ${out_dir}/${id}-tracks-*.json
 done
