Use paging when fetching playlists so it gets ALL of them

diff --git a/shpotify-get-playlists b/shpotify-get-playlists
--- a/shpotify-get-playlists
+++ b/shpotify-get-playlists
@@ -12,16 +12,21 @@ spotify_get() {
     $1
 }
 
-playlists() {
-  if [ ! -e "${out_dir}/playlists.json" ]; then
-    spotify_get https://api.spotify.com/v1/me/playlists > "${out_dir}/playlists.json"
+fetch_playlists() {
+  n=0
+  next_url=https://api.spotify.com/v1/me/playlists
+
+  while [ "$next_url" != "null" ]; do
+    outfile="${out_dir}/playlists-part-${n}.json"
+    spotify_get $next_url > $outfile
     if [ "$?" != "0" ]; then
-      echo 'Playlist get failed' > /dev/stderr
+      echo "Playlist get $next_url failed" > /dev/stderr
       exit 111
     fi
-  fi
 
-  cat "${out_dir}/playlists.json"
+    next_url=$(jq -r '.next' < $outfile)
+    n=$((n+1))
+  done
 }
 
 playlist_vars() {
@@ -42,34 +47,39 @@ remove_old_json_files() {
 
 ensure_clean_git_status
 remove_old_json_files
+fetch_playlists
 
-playlists | jq -c '.items[]' | while read -r playlist_item; do
-  eval "$(echo $playlist_item | playlist_vars)"
-  echo "Getting playlist $name ($id)" > /dev/stderr
+for playlist_chunk in ${out_dir}/playlists-part-*.json; do
+  echo "Processing ${playlist_chunk}" > /dev/stderr
 
-  n=0
-  next_url=$href
+  jq -c '.items[]' < $playlist_chunk | while read -r playlist_item; do
+    eval "$(echo $playlist_item | playlist_vars)"
+    echo "Getting playlist $name ($id)" > /dev/stderr
 
-  while [ "$next_url" != "null" ]; do
-    outfile="${out_dir}/${id}-tracks-${n}.json"
-    if [ ! -e "$outfile" ]; then
-      spotify_get $next_url > $outfile
-      if [ "$?" != "0" ]; then
-        echo 'API call failed' > /dev/stderr
-        exit 111
+    n=0
+    next_url=$href
+
+    while [ "$next_url" != "null" ]; do
+      outfile="${out_dir}/${id}-tracks-${n}.json"
+      if [ ! -e "$outfile" ]; then
+        spotify_get $next_url > $outfile
+        if [ "$?" != "0" ]; then
+          echo 'API call failed' > /dev/stderr
+          exit 111
+        fi
       fi
-    fi
 
-    next_url=$(jq -r '.next' < $outfile)
-    n=$((n+1))
+      next_url=$(jq -r '.next' < $outfile)
+      n=$((n+1))
+    done
+
+    cat $out_dir/$id-tracks-*.json |
+      jq -c '.items[]' > "${out_dir}/${id}-tracks.json"
+
+    echo $playlist_item |
+      jq --slurpfile items ${out_dir}/${id}-tracks.json \
+        '. + { items: $items }' > "${out_dir}/${id}.json"
+
+    rm ${out_dir}/${id}-tracks-*.json ${out_dir}/${id}-tracks.json
   done
-
-  cat $out_dir/$id-tracks-*.json |
-    jq -c '.items[]' > "${out_dir}/${id}-tracks.json"
-
-  echo $playlist_item |
-    jq --slurpfile items ${out_dir}/${id}-tracks.json \
-      '. + { items: $items }' > "${out_dir}/${id}.json"
-
-  rm ${out_dir}/${id}-tracks-*.json ${out_dir}/${id}-tracks.json
 done
